# -*- coding: utf-8 -*-
# -*- mode: ruby -*-
# vi: set ft=ruby :

# load .env file
Dotenv.load

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box       = "dummy"
  config.vm.box_url   = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  config.vm.define "aws-newrelic-test" do |node|
    configure_node(node) do |aws, override|
      aws.ami                    = "ami-29dc9228"  # Amazon Linux AMI 2014.03.2 (HVM)
      aws.instance_type          = "t2.micro"
      aws.tags = {
        "Name" => "aws-newrelic-test",
        "Description" => "New Relic Test",
      }
    end

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/site.yml"
      ansible.extra_vars = {
        newrelic_license_key: ENV['NEWRELIC_LICENSE_KEY']
      }
      ansible.verbose = "v"
    end
  end

  def configure_node(node, &block)
    node.vm.provider :aws do |aws, override|
      # credentials
      aws.access_key_id          = ENV['AWS_ACCESS_KEY_ID']
      aws.secret_access_key      = ENV['AWS_SECRET_ACCESS_KEY']
      aws.keypair_name           = ENV['AWS_KEYPAIR_NAME']

      # EC2 instance settings
      aws.region                 = "ap-northeast-1"
      aws.availability_zone      = "ap-northeast-1a"
      aws.instance_ready_timeout = 120
      aws.terminate_on_shutdown  = false

      aws.security_groups = [ ENV['AWS_SECURITY_GROUP'] ]

      # ssh login settings
      override.ssh.username = ENV['AWS_SSH_USERNAME']
      override.ssh.private_key_path = ENV['AWS_SSH_KEY']

      # suppress errors
      override.vm.synced_folder ".", "/vagrant", disabled: true

      block.call(aws, override)
    end
  end 
end
